#!/bin/sh

export CONFIG_DIR=/BAND/USERS/skp78-dti/dtiplayground/tests/dmriab-test
export OUTPUT_DIR=/BAND/USERS/skp78-dti/test-build-output
export CONFIG=$CONFIG_DIR/data/configs/config.yml
export HBUILD=$CONFIG_DIR/data/configs/h-build.yml
export GREEDY=$CONFIG_DIR/data/configs/GreedyAtlasParameters.xml

source /BAND/USERS/skp78-dti/dtiplayground-env/bin/activate
python ./test.py --output-dir $OUTPUT_DIR --config $CONFIG --hbuild $HBUILD --greedy-params $GREEDY
